### ISSUE TITLE
Profiles

### ISSUE THREAD

**Issue by jorgelucasds** [dailyscape/dailyscape.github.io#3]
Can you add a way to switch between profiles? Would love to run 2 different lists for main/iron

**Comment by 607ch00** [comment]
It's possible yes, I'd want to take my time to think on a clean way to implement it. In the meantime you could setup a different profile in Chrome or Firefox to get the same effect?

**Comment by 607ch00** [comment]
Guess someday was today! Not super happy with the code but it seems to work well. Click the icon in the top right nav bar to get started with profiles :)

**Comment by jorgelucasds** [comment]
Thanks! Will try it out
