### ISSUE TITLE
Buy Port Resources from The Black Marketeer

### ISSUE THREAD

**Issue by FTWImCody** [dailyscape/dailyscape.github.io#40]
https://runescape.wiki/w/The_Black_Marketeer

**Comment by 607ch00** [comment]
I think this is covered under "Player Owned Ports - Manage your player owned port"

**Comment by FTWImCody** [comment]
Maybe add it here? I want to make sure I am not missing anything when doing my Dailies
![image](https://user-images.githubusercontent.com/58948318/216274016-6ecadfcf-2230-4eca-ba4a-d211e8b61596.png)
