### ISSUE TITLE
Deplete resources on claimed island (Uncharted Isles)

### ISSUE THREAD

**Issue by FTWImCody** [dailyscape/dailyscape.github.io#41]
https://runescape.wiki/w/Uncharted_Isles#Claiming_an_island

**Comment by 607ch00** [comment]
There's already an entry for the Arc, this doesn't feel much different if you're doing it daily already

Arc Contracts -Complete up to 7 contracts in the Arc for chimes and xp

**Comment by FTWImCody** [comment]
Maybe do:
Arc - Complete up to 7 contracts in the Arc for chimes and xp
         Deplete Claimed Island
![image](https://user-images.githubusercontent.com/58948318/216274515-053f60ea-34b1-4084-8fbc-e79fbe394736.png)
