### ISSUE TITLE
Travelling merchant stock

### ISSUE THREAD

**Issue by hibob224** [dailyscape/dailyscape.github.io#43]
The current algorithm used to calculate the stock is now no longer 100% accurate, this was expected to happen after 11th Feb. It'll now be incorrect roughly 9% of days.

Doesn't seem like a new algorithm has been worked out yet, at the moment the wiki is just manually overriding items when they are incorrect.

**Comment by 607ch00** [comment]
Thank you for doing what you did. I can't commit to manually updating it lol. Just going to have to leave it be or remove it if it seems to end up being worse than that 91% accuracy

**Comment by hibob224** [comment]
Smarter people than me over at the wiki seem to have cracked a new algorithm, MR submitted

**Comment by 607ch00** [comment]
Ty for the PR again @hibob224 :1st_place_medal: :
