### ISSUE TITLE
Reordering not saved on Chromium

### ISSUE THREAD

**Issue by irfinnew** [dailyscape/dailyscape.github.io#48]
On Chromium 124, I can reorder the items by dragging them, but after a reload everything is back to its original place. No `-order` keys appear in local storage.

I suspect this is unrelated, but on page load I get this warning in the console: `Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'.`

The reorder saving does work correctly on Firefox. Copying the `-order` keys from Firefox into Chromium local storage does make the order work on Chromium.

**Comment by 607ch00** [comment]
Strange, I'm unable to reproduce on chromium 122, but I do see those warnings, so it seems unrelated.  

Chromium 124 isn't available on my main system right now so will need to figure out a different way to reproduce.

**Comment by irfinnew** [comment]
I'm now on Chromium 126 now, and reordering items persists!

Assuming you didn't change anything I'm going to chalk this up as a Chromium bug 🤷🏻‍♀️
